// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221220090846_initial2")]
    partial class initial2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.BMCompanyBranch", b =>
                {
                    b.Property<int>("BM_BranchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BM_BranchID"), 1L, 1);

                    b.Property<bool?>("Accounts")
                        .HasColumnType("bit");

                    b.Property<bool?>("ActiveStatus")
                        .HasColumnType("bit");

                    b.Property<bool?>("AllowStockValueFIFO")
                        .HasColumnType("bit");

                    b.Property<bool?>("AllowStockValueLIFO")
                        .HasColumnType("bit");

                    b.Property<bool?>("AllowStockValueWAVGPeriodical")
                        .HasColumnType("bit");

                    b.Property<bool?>("AllowStockValueWAVGPerpetual")
                        .HasColumnType("bit");

                    b.Property<string>("BM_BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BM_BranchName1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BM_BranchName2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BM_BranchName_0")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BM_BranchName_1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BM_BranchName_2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BM_BranchName_3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BM_BranchName_4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BM_BranchName_PSRF_Short")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BM_CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BooksBegginingFrom")
                        .HasColumnType("datetime2");

                    b.Property<string>("BranchLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BusinessType_BMItemID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompanyEstablishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorporateOfficeAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EBS_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EBS_InterCompanyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EBS_LegalEntityCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EBS_OU_ID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EBS_OU_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinancialYearFrom")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("Flag")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("HirePurchase")
                        .HasColumnType("bit");

                    b.Property<string>("IncomeTexNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Inventory")
                        .HasColumnType("bit");

                    b.Property<string>("Ledger_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalEntityAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalEntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("LocalDataEntryLocked")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Manager_HR_EmployeeID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PINCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Procurement")
                        .HasColumnType("bit");

                    b.Property<bool?>("Production")
                        .HasColumnType("bit");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Sales")
                        .HasColumnType("bit");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("TreatCurrentBranch")
                        .HasColumnType("bit");

                    b.Property<bool?>("TreatHeadOffice")
                        .HasColumnType("bit");

                    b.Property<decimal?>("VATForGeneralSales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VATForHirePurchase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VATForPurchase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VATForShowroom")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VatTIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sap_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BM_BranchID");

                    b.ToTable("BM_CompanyBranch", (string)null);
                });

            modelBuilder.Entity("Domain.BMConcurrentRequest", b =>
                {
                    b.Property<long>("PID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PID"), 1L, 1);

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CreatedByUserID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ErrorSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutableString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("LastUpdateByUserID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NotifyUser")
                        .HasColumnType("int");

                    b.Property<string>("OutputFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputFileURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReferenceID")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestParameter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetProcessManager")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PID");

                    b.ToTable("BM_ConcurrentRequest", (string)null);
                });

            modelBuilder.Entity("Domain.BMSecUser", b =>
                {
                    b.Property<decimal>("BM_UserID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AcceptERPAgreement")
                        .HasColumnType("int");

                    b.Property<int?>("AcceptPolicy")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BM_BranchID")
                        .HasColumnType("int");

                    b.Property<string>("ConfirmPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EmailDeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailForward")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FailedAttemptsTime")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("Flag")
                        .HasColumnType("tinyint");

                    b.Property<int?>("HR_DeptID")
                        .HasColumnType("int");

                    b.Property<int?>("HR_DesgID")
                        .HasColumnType("int");

                    b.Property<decimal?>("HR_EmployeeID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Inactive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("LoanAdvanceFinalized")
                        .HasColumnType("bit");

                    b.Property<bool?>("LoanAdvanceStart")
                        .HasColumnType("bit");

                    b.Property<string>("LogUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MACAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PasswordVerified")
                        .HasColumnType("int");

                    b.Property<string>("Phone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("PunchCardNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Relegion_BM_ItemID")
                        .HasColumnType("int");

                    b.Property<int?>("Sex_BM_ItemID")
                        .HasColumnType("int");

                    b.Property<string>("SignaturePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BM_UserID");

                    b.ToTable("BM_SecUser", (string)null);
                });

            modelBuilder.Entity("Domain.HrEmployee", b =>
                {
                    b.Property<decimal>("HR_EmployeeID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Acc_BankID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Acc_ForfeitureAccountID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Acc_RetiredMembersAccountID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<decimal?>("AdditionalReportTo1_EmployeeID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AdditionalReportTo2_EmployeeID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AppStatusBM_ItemIDUsers")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BM_BranchID")
                        .HasColumnType("int");

                    b.Property<string>("BankAccountNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("BasicSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BloodBM_ItemID")
                        .HasColumnType("int");

                    b.Property<string>("CardNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CauseOfSeparation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CauseOfSeparationBM_ItemID")
                        .HasColumnType("int");

                    b.Property<decimal?>("ClosingBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ConfirmationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmationDateApprox")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ContractualDateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ContractualDateTo")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CorporateTitleBM_ItemIDUsers")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DateOfBirthV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfJoining")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DistrictBM_ItemIDUsers")
                        .HasColumnType("int");

                    b.Property<decimal?>("DottedLine2_EmployeeID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DottedLineHR_EmployeeID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EBS_CostCenterID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EBS_EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EBS_LocationID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeFileLocationBM_ItemIDUsers")
                        .HasColumnType("int");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraCurricularActivities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Father_HushandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FinalPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Flag")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("ForfeitureAC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FunctionalLevelBM_ItemID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("GenderBM_ItemID")
                        .HasColumnType("int");

                    b.Property<int?>("GrandeBM_ItemIDUsers")
                        .HasColumnType("int");

                    b.Property<int?>("GratuatyAfterYear")
                        .HasColumnType("int");

                    b.Property<bool?>("GratuatyEnable")
                        .HasColumnType("bit");

                    b.Property<decimal?>("HRMappedRoleId")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("HRRoleId")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("HR_BandID")
                        .HasColumnType("int");

                    b.Property<int?>("HR_DeptID")
                        .HasColumnType("int");

                    b.Property<int?>("HR_DesgID")
                        .HasColumnType("int");

                    b.Property<string>("HR_EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HR_GradeID")
                        .HasColumnType("int");

                    b.Property<bool?>("HoldSalary")
                        .HasColumnType("bit");

                    b.Property<string>("HoldSalaryReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Inactive")
                        .HasColumnType("bit");

                    b.Property<string>("InternetBillType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("InternetLimit")
                        .HasColumnType("float");

                    b.Property<int?>("InternetOperatorBM_ItemID")
                        .HasColumnType("int");

                    b.Property<int?>("JobLevelBM_ItemIDUsers")
                        .HasColumnType("int");

                    b.Property<DateTime?>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LPRPaymentID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaritalStatusBM_ItemID")
                        .HasColumnType("int");

                    b.Property<string>("Mgr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MinimumDaysOfConfirmation")
                        .HasColumnType("int");

                    b.Property<string>("MobileBillType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("MobileLimit")
                        .HasColumnType("float");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NationalityInv_CountryID")
                        .HasColumnType("int");

                    b.Property<int?>("NoBonus")
                        .HasColumnType("int");

                    b.Property<string>("Nominee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureNameForWeb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PicturePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlaceOfPostingBM_ItemIDUsers")
                        .HasColumnType("int");

                    b.Property<string>("PresentMailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ProcessForLPR")
                        .HasColumnType("bit");

                    b.Property<string>("ProfessionalQualification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RelagionBM_ItemID")
                        .HasColumnType("int");

                    b.Property<decimal?>("ReportTo2_EmployeeID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ReportToHR_EmployeeID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RetireDateActual")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RetireDateApproximate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Rtd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SF_ID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalaryAccountAcc_BankID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SalaryScaleBM_ItemIDUsers")
                        .HasColumnType("int");

                    b.Property<decimal?>("SalarySheetSerialNo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SpeakFluencyInLanInv_CountryID")
                        .HasColumnType("int");

                    b.Property<int?>("SpeakFluencyPerfoBM_ItemID")
                        .HasColumnType("int");

                    b.Property<string>("SpouseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalPayableAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrainingInBrief")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("UnderHR_EmployeeID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UnderHR_EmployeeIDLast")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Under_Acc_HeadFirstLvlName")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Village")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoterIDNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WPPF_EligibleAs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eTIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sap_area_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sap_bu_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sap_func_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sap_subArea_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sap_subFunc_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sap_support_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("suspensionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("HR_EmployeeID");

                    b.ToTable("HR_Employee", (string)null);
                });

            modelBuilder.Entity("Domain.UM_MENU_ACCESS_V", b =>
                {
                    b.Property<string>("ADDRESSMENAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AGDESCHELP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("AGID")
                        .HasColumnType("bigint");

                    b.Property<string>("AGNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("APP_ICONNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("APP_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("APP_SHORTCODE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CANDELETE")
                        .HasColumnType("int");

                    b.Property<int>("CANINSERT")
                        .HasColumnType("int");

                    b.Property<int>("CANUPDATE")
                        .HasColumnType("int");

                    b.Property<int>("CANVIEW")
                        .HasColumnType("int");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EMP_ID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ICONNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ICONNAME_MG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("INACTIVE_MENU")
                        .HasColumnType("bit");

                    b.Property<bool?>("INACTIVE_MENUGROUP")
                        .HasColumnType("bit");

                    b.Property<bool?>("INACTIVE_RSP_ASSIGNMENT")
                        .HasColumnType("bit");

                    b.Property<bool?>("INACTIVE_USER")
                        .HasColumnType("bit");

                    b.Property<bool?>("INCATIVE_ACCESS_GP")
                        .HasColumnType("bit");

                    b.Property<bool?>("INCATIVE_RSP")
                        .HasColumnType("bit");

                    b.Property<string>("LOGINID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOGINNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LOOKUP_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("MENUDESCHELP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MENUNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MENUSHORTNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MENUTOOLTIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MGID")
                        .HasColumnType("bigint");

                    b.Property<string>("MGNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MGRUOUTENAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MGSERIALNO")
                        .HasColumnType("int");

                    b.Property<string>("MGTOOLTIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MID")
                        .HasColumnType("bigint");

                    b.Property<string>("ROUTINGNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RSPDESC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RSPID")
                        .HasColumnType("bigint");

                    b.Property<string>("RSPNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SERIAL_NO")
                        .HasColumnType("bigint");

                    b.Property<string>("SHORTCODE_MG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("USERID")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("UM_MENU_ACCESS_V");
                });

            modelBuilder.Entity("Domain.UmResponsibilityAssign", b =>
                {
                    b.Property<long>("RSPAGID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RSPAGID"), 1L, 1);

                    b.Property<long?>("CREATED_BY")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CREATION_DATE")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IS_INACTIVE")
                        .HasColumnType("bit");

                    b.Property<long?>("LAST_UPDATE_BY")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LAST_UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("REMARKS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RSPID")
                        .HasColumnType("bigint");

                    b.Property<long>("USERID")
                        .HasColumnType("bigint");

                    b.HasKey("RSPAGID");

                    b.ToTable("UM_RESPONSIBILITYASSIGN", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
